CREATE DATABASE IF NOT EXISTS sigeca;

USE sigeca;

DROP TABLE IF EXISTS medidas_adolescentes;
DROP TABLE IF EXISTS condiciones_adolescentes;
DROP TABLE IF EXISTS colab_medidas_adolescentes;
DROP TABLE IF EXISTS colab_condicones_adolescentes;
DROP TABLE IF EXISTS colab_jefaturas;
DROP TABLE IF EXISTS colab_externas;
DROP TABLE IF EXISTS eval_adolescentes;
DROP TABLE IF EXISTS reevaluaciones;

CREATE TABLE IF NOT EXISTS medidas_adolescentes(
	a_paterno VARCHAR(50) NOT NULL DEFAULT 'S/D',
	a_materno VARCHAR(50) NOT NULL DEFAULT 'S/D',
	nombre VARCHAR(50) NOT NULL DEFAULT 'S/D',
	edad TINYINT(3) UNSIGNED,
	num_causa VARCHAR(10),
	juez_control VARCHAR(255) DEFAULT 'S/D',
	juzgado_control VARCHAR(255) DEFAULT 'S/D',
	distrito_judicial VARCHAR(255) DEFAULT 'S/D',
	supervisor_asignado VARCHAR(255) DEFAULT 'S/D',
	municipio_radicacion VARCHAR(255) DEFAULT 'S/D',
	colonia VARCHAR(255) DEFAULT 'S/D',
	calle VARCHAR(255) DEFAULT 'S/D',
	numero VARCHAR(10) DEFAULT 'S/D',
	clasificacion_delito VARCHAR(100) DEFAULT 'S/D',
	descripcion_delito TEXT NOT NULL,
	seguimiento VARCHAR(50) DEFAULT 'S/D',
	fecha_inicio DATE,
	fecha_termino DATE,
	fecha_real_conclusion DATE,
	medidaI VARCHAR(2),
	medidaII VARCHAR(2),
	medidaIII VARCHAR(2),
	medidaIV VARCHAR(2),
	medidaV VARCHAR(2),
	medidaVI VARCHAR(2),
	medidaVII VARCHAR(2),
	medidaVIII VARCHAR(2),
	medidaIX VARCHAR(2),
	medidaX VARCHAR(2),
	medidaXI VARCHAR(2),
	medidaXII VARCHAR(2),
	num_medidas VARCHAR (2),
	medidas_dictadas TEXT,
	cumplimiento VARCHAR(10),
	fecha_incumplimiento DATE,
	medida_incumplida VARCHAR(100),
	fecha_modificacionI DATE,
	tipo_modificacionI VARCHAR(20),
	fecha_modificacionII DATE,
	tipo_modificacionII VARCHAR(50),
	proxima_audiencia DATE,
	audiencias_asistidas VARCHAR(3),
	total_audiencias VARCHAR(2),
	tta VARCHAR(10),
	observaciones TEXT,
	genero VARCHAR(10) DEFAULT 'S/D',
	ultima_act_expediente VARCHAR (100),
	forma_conclusion VARCHAR(100)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
	
	CREATE TABLE IF NOT EXISTS condiciones_adolescentes(
	num_supervision VARCHAR(30),
	fecha_solicitud DATE,
	num_evaluacion VARCHAR(30),
	a_paterno VARCHAR(50),
	a_materno VARCHAR(50),
	nombre VARCHAR(50),
	edad TINYINT(3) UNSIGNED,
	num_causa VARCHAR(10),
	juez_control VARCHAR(255),
	juzgado_control VARCHAR(50),
	distrito_judicial VARCHAR(50),
	supervisor_asignado VARCHAR(100),
	municipio_radicacion VARCHAR(50),
	colonia VARCHAR(50),
	calle VARCHAR(50),
	numero VARCHAR(30),
	clasificacion_delito VARCHAR(100),
	descripcion_delito TEXT,
	seguimiento VARCHAR(20),
	fecha_inicio DATE,
	fecha_termino DATE,
	fecha_real_conclusion DATE,
	condicionI VARCHAR(2),
	condicionII VARCHAR(2),
	condicionIII VARCHAR(2),
	condicionIV VARCHAR(2),
	condicionV VARCHAR(2),
	condicionVI VARCHAR(2),
	condicionVII VARCHAR(2),
	num_condiciones VARCHAR(2),
	condiciones_impuestas TEXT,
	cumplimiento VARCHAR(10),
	fecha_incumplimiento DATE,
	condicion_incumplida VARCHAR(50),
	fecha_modificacionI DATE,
	tipo_modificacionI VARCHAR(50),
	fecha_modificacionII DATE,
	tipo_modificacionII VARCHAR(50),
	audiencias_asistidas VARCHAR(30),
	total_audiencias VARCHAR(3),
	tta VARCHAR(3),
	observaciones TEXT,
	genero VARCHAR(10),
	ultima_act_expediente VARCHAR(100),
	forma_conclusion VARCHAR(100)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
	
	CREATE TABLE IF NOT EXISTS colab_medidas_adolescentes(
	num_supervision VARCHAR(30),
	fecha_solicitud DATE,
	num_colaboracion VARCHAR(5),
	a_paterno VARCHAR(50),
	a_materno VARCHAR(50),
	nombre VARCHAR(50),
	edad TINYINT(3) UNSIGNED,
	autoridad_solicitante VARCHAR(100),
	procedencia VARCHAR(30),
	juez_control VARCHAR(100),
	juzgado_control VARCHAR(50),
	distrito_judicial VARCHAR(50),
	supervisor_asignado VARCHAR(100),
	municipio_radicacion VARCHAR(50),
	colonia VARCHAR(50),
	calle VARCHAR(50),
	numero VARCHAR(30),
	clasificacion_delito VARCHAR(100),
	descripcion_delito TEXT,
	seguimiento VARCHAR(20),
	fecha_inicio DATE,
	fecha_termino DATE,
	fecha_real_conclusion DATE,
	medidaI VARCHAR(2),
	medidaII VARCHAR(2),
	medidaIII VARCHAR(2),
	medidaIV VARCHAR(2),
	medidaV VARCHAR(2),
	medidaVI VARCHAR(2),
	medidaVII VARCHAR(2),
	medidaVIII VARCHAR(2),
	medidaIX VARCHAR(2),
	medidaX VARCHAR(2),
	medidaXI VARCHAR(2),
	medidaXII VARCHAR(2),
	num_medidas VARCHAR (2),
	medidas_impuestas TEXT,
	cumplimiento VARCHAR(10),
	fecha_incumplimiento DATE,
	medida_incumplida VARCHAR(100),
	fecha_modificacionI DATE,
	tipo_modificacionI VARCHAR(20),
	fecha_modificacionII DATE,
	tipo_modificacionII VARCHAR(50),
	proxima_audiencia DATE,
	audiencias_asistidas VARCHAR(3),
	total_audiencias VARCHAR(2),
	tta VARCHAR(10),
	observaciones TEXT,
	supervisor_asignadoI VARCHAR(100),
	genero VARCHAR(10),
	ultima_act_expediente VARCHAR(100),
	forma_conclusion VARCHAR(100)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
	
	CREATE TABLE IF NOT EXISTS colab_condicones_adolescentes(
	num_supervision VARCHAR(30),
	fecha_solicitud DATE,
	num_colaboracion VARCHAR(5),
	a_paterno VARCHAR(50),
	a_materno VARCHAR(50),
	nombre VARCHAR(50),
	edad TINYINT(3) UNSIGNED,
	num_causa VARCHAR(50),
	autoridad_solicitante VARCHAR(100),
	procedencia VARCHAR(30),
	juez_control VARCHAR(100),
	juzgado_control VARCHAR(50),
	distrito_judicial VARCHAR(50),
	supervisor_asignado VARCHAR(100),
	municipio_radicacion VARCHAR(50),
	colonia VARCHAR(50),
	calle VARCHAR(50),
	numero VARCHAR(30),
	clasificacion_delito VARCHAR(100),
	descripcion_delito TEXT,
	seguimiento VARCHAR(20),
	fecha_inicio DATE,
	fecha_termino DATE,
	fecha_real_conclusion DATE,
	condicionI VARCHAR(2),
	condicionII VARCHAR(2),
	condicionIII VARCHAR(2),
	condicionIV VARCHAR(2),
	condicionV VARCHAR(2),
	condicionVI VARCHAR(2),
	condicionVII VARCHAR(2),
	num_condiciones VARCHAR(2),
	condiciones_impuestas TEXT,
	cumplimiento VARCHAR(10),
	fecha_incumplimiento DATE,
	condicion_incumplida VARCHAR(50),
	fecha_modificacionI DATE,
	tipo_modificacionI VARCHAR(50),
	fecha_modificacionII DATE,
	tipo_modificacionII VARCHAR(50),
	proxima_audiencia DATE,
	audiencias_asistidas VARCHAR(30),
	total_audiencias VARCHAR(3),
	tta VARCHAR(3),
	observaciones TEXT,
	supervisor_asignadoI VARCHAR(100),
	genero VARCHAR(10),
	ultima_act_expediente VARCHAR(100),
	forma_conclusion VARCHAR(100)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
	
	CREATE TABLE IF NOT EXISTS colab_jefaturas(
	num_expediente VARCHAR(30),
	fecha_solicitud DATE,
	a_paterno VARCHAR(50),
	a_materno VARCHAR(50),
	nombre VARCHAR(50),
	num_causa_control VARCHAR(30),
	jefatura_procedencia VARCHAR(30),
	supervisor_asignado VARCHAR(100),
	delito VARCHAR(255),
	fecha_inicio_medida_cuatelar DATE,
	fecha_termino_medida_cautelar DATE,
	fecha_conclusion_mc DATE,
	fecha_inicio_susp_condiconal DATE,
	fecha_termino_susp_condiconal DATE,
	fecha_conclusion_sc DATE,
	i VARCHAR(2),
	ii VARCHAR(2),
	iii VARCHAR(2),
	iv VARCHAR(2),
	v VARCHAR(2),
	vi VARCHAR(2),
	vii VARCHAR(2),
	viii VARCHAR(2),
	ix VARCHAR(2),
	x VARCHAR(2),
	xi VARCHAR(2),
	xii VARCHAR(2),
	xiii VARCHAR(2),
	xiv VARCHAR(2),
	cantidad_medidas VARCHAR(2),
	cantidad_condiciones VARCHAR(3),
	fecha_recepcion_cese DATE,
	fecha_entrega_act DATE,
	observaciones TEXT) ENGINE=InnoDB DEFAULT CHARSET=utf8;
	
	CREATE TABLE IF NOT EXISTS colab_externas(
	num_supervision VARCHAR(30),
	fecha_recepcion DATE,
	num_oficio VARCHAR(50),
	num_carpeta VARCHAR(50),
	autoridad_solicitante VARCHAR(30),
	nombre_imputado VARCHAR(100),
	delito VARCHAR(30),
	municipio VARCHAR(30),
	nombre_supervisor VARCHAR(100),
	accion_realizar VARCHAR(50),
	fecha_actuacion DATE,
	fecha_emision DATE,
	acuse_recepcion DATE,
	observaciones TEXT,
	archivo VARCHAR(50),
	actividades VARCHAR(50)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
	
	CREATE TABLE IF NOT EXISTS eval_adolescentes (
    evaluacion VARCHAR(50),
    reevaluacion VARCHAR(50),
    carpeta_administrativa VARCHAR(100),
    juzgado VARCHAR(255),
    fecha_recepcion DATE,
    hora_recepcion TIME,
    fuero VARCHAR(50),
    fiscalia VARCHAR(255),
    agencia VARCHAR(255),
    ministerio_publico VARCHAR(255),
    turno VARCHAR(50),
    telefono VARCHAR(50),
    email VARCHAR(255),
    carpeta_investigacion VARCHAR(255),
    falla_tecnica VARCHAR(100),
    nuc VARCHAR(100),
    nic VARCHAR(100),
    fecha_disposicion DATE,
    hora_disposicion TIME,
    puesta_disposicion VARCHAR(100),
    paterno VARCHAR(50),
    materno VARCHAR(50),
    nombre VARCHAR(50),
    curp VARCHAR(50),
    edad TINYINT,
    genero VARCHAR(20),
    municipio VARCHAR(100),
    colonia VARCHAR(100),
    calle VARCHAR(100),
    numero VARCHAR(50),
    municipio_delito VARCHAR(100),
    colonia_delito VARCHAR(100),
    descripcion_delito VARCHAR(255),
    catalogo1 VARCHAR(50),
    catalogo2 VARCHAR(50),
    catalogo3 VARCHAR(50),
    catalogo4 VARCHAR(50),
    subdireccion VARCHAR(100),
    distrito_judicial VARCHAR(100),
    evaluador VARCHAR(100),
    tipo_atencion VARCHAR(100),
    tutor VARCHAR(100),
    fecha_entrevista DATE,
    hora_entrevista TIME,
    defensor VARCHAR(100),
    tipo_riesgo VARCHAR(50),
    riesgo_168 VARCHAR(50),
    riesgo_169 VARCHAR(50),
    riesgo_170 VARCHAR(50),
    fecha_envio DATE,
    hora_envio TIME,
    estado VARCHAR(50),
    verificado VARCHAR(10),
    tipo_verificacion VARCHAR(50),
    observaciones TEXT)ENGINE=InnoDB DEFAULT CHARSET=utf8;
	
	CREATE TABLE IF NOT EXISTS reevaluaciones (
    evaluacion VARCHAR(50),
    reevaluacion VARCHAR(50),
    carpeta_administrativa VARCHAR(100),
    juzgado VARCHAR(255),
    fecha_recepcion DATE,
    hora_recepcion TIME,
    fuero VARCHAR(50),
    fiscalia VARCHAR(255),
    agencia VARCHAR(255),
    juez_control VARCHAR(255),
    turno VARCHAR(50),
    telefono VARCHAR(50),
    email VARCHAR(255),
    carpeta_investigacion VARCHAR(255),
    falla_tecnica VARCHAR(100),
    nuc VARCHAR(100),
    nic VARCHAR(100),
    fecha_disposicion DATE,
    hora_disposicion TIME,
    puesta_disposicion VARCHAR(100),
    paterno VARCHAR(50),
    materno VARCHAR(50),
    nombre VARCHAR(50),
    curp VARCHAR(50),
    rfc VARCHAR(50),
    edad TINYINT,
    genero VARCHAR(20),
    municipio VARCHAR(100),
    colonia VARCHAR(100),
    calle VARCHAR(100),
    numero VARCHAR(50),
    municipio_delito VARCHAR(100),
    colonia_delito VARCHAR(100),
    descripcion_delito VARCHAR(255),
    delito1 VARCHAR(255),
    delito2 VARCHAR(255),
    delito3 VARCHAR(255),
    delito4 VARCHAR(255),
    subdireccion VARCHAR(100),
    distrito_judicial VARCHAR(100),
    evaluador VARCHAR(100),
    tipo_atencion VARCHAR(100),
    fecha_entrevista DATE,
    hora_entrevista TIME,
    defensor VARCHAR(100),
    tipo_riesgo VARCHAR(50),
    nuevo_tipo_riesgo VARCHAR(50),
    riesgo168 VARCHAR(50),
    riesgo169 VARCHAR(50),
    riesgo170 VARCHAR(50),
    fecha_envio DATE,
    hora_envio TIME,
    estado VARCHAR(50),
    verificada VARCHAR(10),
    tipo_verificacion VARCHAR(50),
    observaciones TEXT) ENGINE=InnoDB DEFAULT CHARSET=utf8;