CREATE DATABASE IF NOT EXISTS sigeca;

USE sigeca;

DROP TABLE IF EXISTS eval_adolescentes;
DROP TABLE IF EXISTS reevaluaciones;

CREATE TABLE tipos_usuario_sigeca (
   id int NOT NULL AUTO_INCREMENT,
   tipo varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS usuario_sigeca (
    idusuario INT NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(50) NOT NULL,
    usuario VARCHAR(20) NOT NULL,
    contrasena VARCHAR(20) NOT NULL,
    fecha_alta DATE NOT NULL,
    tipo_usuario_id INT,
    estado TINYINT(1) NULL DEFAULT 1,
    PRIMARY KEY (idusuario),
    FOREIGN KEY (tipo_usuario_id) REFERENCES tipos_usuario(id)
)ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS eval_adolescentes (
    evaluacion VARCHAR(100),
    reevaluacion VARCHAR(100),
    carpeta_administrativa VARCHAR(150),
    juzgado VARCHAR(255),
    fecha_recepcion DATE,
    hora_recepcion TIME,
    fuero VARCHAR(50),
    fiscalia VARCHAR(300),
    agencia VARCHAR(300),
    ministerio_publico VARCHAR(300),
    turno VARCHAR(100),
    telefono VARCHAR(100),
    email VARCHAR(255),
    carpeta_investigacion VARCHAR(255),
    falla_tecnica VARCHAR(150),
    nuc VARCHAR(150),
    nic VARCHAR(150),
    fecha_disposicion DATE,
    hora_disposicion TIME,
    puesta_disposicion VARCHAR(150),
    paterno VARCHAR(50),
    materno VARCHAR(50),
    nombre VARCHAR(100),
    curp VARCHAR(50),
    edad VARCHAR(5),
    genero VARCHAR(50),
    municipio VARCHAR(100),
    colonia VARCHAR(100),
    calle VARCHAR(150),
    numero VARCHAR(50),
    municipio_delito VARCHAR(100),
    colonia_delito VARCHAR(100),
    descripcion_delito VARCHAR(1000),
    catalogo1 VARCHAR(300),
    catalogo2 VARCHAR(300),
    catalogo3 VARCHAR(300),
    catalogo4 VARCHAR(300),
    subdireccion VARCHAR(100),
    distrito_judicial VARCHAR(100),
    evaluador VARCHAR(200),
    tipo_atencion VARCHAR(255),
    tutor VARCHAR(50),
    fecha_entrevista DATE,
    hora_entrevista TIME,
    defensor VARCHAR(100),
    tipo_riesgo VARCHAR(70),
    riesgo_168 VARCHAR(50),
    riesgo_169 VARCHAR(50),
    riesgo_170 VARCHAR(50),
    fecha_envio DATE,
    hora_envio TIME,
    estado VARCHAR(150),
    verificado VARCHAR(10),
    tipo_verificacion VARCHAR(70),
    observaciones TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS reevaluaciones (
    evaluacion VARCHAR(100),
    reevaluacion VARCHAR(100),
    carpeta_administrativa VARCHAR(150),
    juzgado VARCHAR(255),
    fecha_recepcion DATE,
    hora_recepcion TIME,
    fuero VARCHAR(50),
    fiscalia VARCHAR(300),
    agencia VARCHAR(300),
    juez_control VARCHAR(300),
    turno VARCHAR(100),
    telefono VARCHAR(50),
    email VARCHAR(255),
    carpeta_investigacion VARCHAR(300),
    falla_tecnica VARCHAR(150),
    nuc VARCHAR(150),
    nic VARCHAR(150),
    fecha_disposicion DATE,
    hora_disposicion TIME,
    puesta_disposicion VARCHAR(150),
    paterno VARCHAR(50),
    materno VARCHAR(50),
    nombre VARCHAR(100),
    curp VARCHAR(50),
    rfc VARCHAR(50),
    edad VARCHAR(5),
    genero VARCHAR(20),
    municipio VARCHAR(100),
    colonia VARCHAR(100),
    calle VARCHAR(150),
    numero VARCHAR(50),
    municipio_delito VARCHAR(100),
    colonia_delito VARCHAR(100),
    descripcion_delito VARCHAR(1000),
    delito1 VARCHAR(300),
    delito2 VARCHAR(300),
    delito3 VARCHAR(300),
    delito4 VARCHAR(300),
    subdireccion VARCHAR(100),
    distrito_judicial VARCHAR(100),
    evaluador VARCHAR(200),
    tipo_atencion VARCHAR(150),
    fecha_entrevista DATE,
    hora_entrevista TIME,
    defensor VARCHAR(100),
    tipo_riesgo VARCHAR(50),
    nuevo_tipo_riesgo VARCHAR(50),
    riesgo168 VARCHAR(50),
    riesgo169 VARCHAR(50),
    riesgo170 VARCHAR(50),
    fecha_envio DATE,
    hora_envio TIME,
    estado VARCHAR(100),
    verificada VARCHAR(10),
    tipo_verificacion VARCHAR(50),
    observaciones TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
