CREATE DATABASE IF NOT EXISTS sigeca;

USE sigeca;

DROP TABLE IF EXISTS eval_adolescentes;
DROP TABLE IF EXISTS reevaluaciones;
DROP TABLE IF EXISTS medidas_adolescentes;
DROP TABLE IF EXISTS condiciones_adolescentes;
DROP TABLE IF EXISTS colab_medidas_adolescentes;
DROP TABLE IF EXISTS colab_condiciones_adolescentes;
DROP TABLE IF EXISTS eval_adultos;


CREATE TABLE tipos_usuario_sigeca (
   id int NOT NULL AUTO_INCREMENT,
   tipo varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS usuario_sigeca (
    idusuario INT NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(50) NOT NULL,
    usuario VARCHAR(20) NOT NULL,
    contrasena VARCHAR(20) NOT NULL,
    fecha_alta DATE NOT NULL,
    tipo_usuario_id INT,
    estado TINYINT(1) NULL DEFAULT 1,
    avatar VARCHAR(255),
    PRIMARY KEY (idusuario),
    FOREIGN KEY (tipo_usuario_id) REFERENCES tipos_usuario(id)
)ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS eval_adolescentes (
    evaluacion VARCHAR(100),
    reevaluacion VARCHAR(100),
    carpeta_administrativa VARCHAR(150),
    juzgado VARCHAR(255),
    fecha_recepcion DATE,
    hora_recepcion TIME,
    fuero VARCHAR(50),
    fiscalia VARCHAR(300),
    agencia VARCHAR(300),
    ministerio_publico VARCHAR(300),
    turno VARCHAR(100),
    telefono VARCHAR(100),
    email VARCHAR(255),
    carpeta_investigacion VARCHAR(255),
    falla_tecnica VARCHAR(150),
    nuc VARCHAR(150),
    nic VARCHAR(150),
    fecha_disposicion DATE,
    hora_disposicion TIME,
    puesta_disposicion VARCHAR(150),
    paterno VARCHAR(50),
    materno VARCHAR(50),
    nombre VARCHAR(100),
    curp VARCHAR(50),
    edad VARCHAR(5),
    genero VARCHAR(50),
    municipio VARCHAR(100),
    colonia VARCHAR(100),
    calle VARCHAR(150),
    numero VARCHAR(50),
    municipio_delito VARCHAR(100),
    colonia_delito VARCHAR(100),
    descripcion_delito VARCHAR(1000),
    catalogo1 VARCHAR(300),
    catalogo2 VARCHAR(300),
    catalogo3 VARCHAR(300),
    catalogo4 VARCHAR(300),
    subdireccion VARCHAR(100),
    distrito_judicial VARCHAR(100),
    evaluador VARCHAR(200),
    tipo_atencion VARCHAR(255),
    tutor VARCHAR(50),
    fecha_entrevista DATE,
    hora_entrevista TIME,
    defensor VARCHAR(100),
    tipo_riesgo VARCHAR(70),
    riesgo_168 VARCHAR(50),
    riesgo_169 VARCHAR(50),
    riesgo_170 VARCHAR(50),
    fecha_envio DATE,
    hora_envio TIME,
    estado VARCHAR(150),
    verificado VARCHAR(10),
    tipo_verificacion VARCHAR(70),
    observaciones TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS reevaluaciones (
    evaluacion VARCHAR(100),
    reevaluacion VARCHAR(100),
    carpeta_administrativa VARCHAR(150),
    juzgado VARCHAR(255),
    fecha_recepcion DATE,
    hora_recepcion TIME,
    fuero VARCHAR(50),
    fiscalia VARCHAR(300),
    agencia VARCHAR(300),
    juez_control VARCHAR(300),
    turno VARCHAR(100),
    telefono VARCHAR(50),
    email VARCHAR(255),
    carpeta_investigacion VARCHAR(300),
    falla_tecnica VARCHAR(150),
    nuc VARCHAR(150),
    nic VARCHAR(150),
    fecha_disposicion DATE,
    hora_disposicion TIME,
    puesta_disposicion VARCHAR(150),
    paterno VARCHAR(50),
    materno VARCHAR(50),
    nombre VARCHAR(100),
    curp VARCHAR(50),
    rfc VARCHAR(50),
    edad VARCHAR(5),
    genero VARCHAR(20),
    municipio VARCHAR(100),
    colonia VARCHAR(100),
    calle VARCHAR(150),
    numero VARCHAR(50),
    municipio_delito VARCHAR(100),
    colonia_delito VARCHAR(100),
    descripcion_delito VARCHAR(1000),
    delito1 VARCHAR(300),
    delito2 VARCHAR(300),
    delito3 VARCHAR(300),
    delito4 VARCHAR(300),
    subdireccion VARCHAR(100),
    distrito_judicial VARCHAR(100),
    evaluador VARCHAR(200),
    tipo_atencion VARCHAR(150),
    fecha_entrevista DATE,
    hora_entrevista TIME,
    defensor VARCHAR(100),
    tipo_riesgo VARCHAR(50),
    nuevo_tipo_riesgo VARCHAR(50),
    riesgo168 VARCHAR(50),
    riesgo169 VARCHAR(50),
    riesgo170 VARCHAR(50),
    fecha_envio DATE,
    hora_envio TIME,
    estado VARCHAR(100),
    verificada VARCHAR(10),
    tipo_verificacion VARCHAR(50),
    observaciones TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS eval_adultos(
	evaluacion VARCHAR(20) NOT NULL,
    reevaluacion VARCHAR(255) NOT NULL,
    carpeta_administrativa VARCHAR(255) default 'S/D',
    juzgado VARCHAR(255)  default 'S/D',
    fecha_recepcion DATE,
    hora_recepcion TIME,
    fuero VARCHAR(20),
    fiscalia VARCHAR(255) default 'S/D',
    agencia TEXT,
    ministerio_publico VARCHAR(255) DEFAULT 'S/D',
    turno VARCHAR(100) DEFAULT 'S/D',
    telefono VARCHAR(10) DEFAULT 'S/D',
    email TEXT,
    carpeta_investigacion TEXT,
    falla_tecnica TEXT ,
    nuc TEXT,
    nic TEXT,
    fecha_disposicion DATE,
    hora_disposicion TIME,
    puesta_disposicion VARCHAR(256),
    paterno VARCHAR(255) NOT NULL DEFAULT 'S/D',
    materno VARCHAR(255) NOT NULL DEFAULT 'S/D',
    nombre VARCHAR(255) NOT NULL DEFAULT 'S/D',
    curp VARCHAR(255) NOT NULL DEFAULT 'S/D',
    rfc VARCHAR(13) NOT NULL DEFAULT 'S/D',
    edad VARCHAR(2),
    genero VARCHAR(20) DEFAULT 'S/D',
    municipio VARCHAR(256) DEFAULT 'S/D',
    colonia VARCHAR(256) DEFAULT 'S/D',
    calle VARCHAR(256) DEFAULT 'S/D',
    numero VARCHAR(10) DEFAULT 'S/D',    
    municipio_delito VARCHAR(255) DEFAULT 'S/D',
    colonia_delito TEXT,
    descripcion_delito TEXT NOT NULL,
    catalogo1 TEXT NOT NULL,
    catalogo2 TEXT,
    catalogo3 TEXT,
    catalogo4 TEXT,
    subdireccion VARCHAR(25) NOT NULL,
    distrito_judicial VARCHAR(100) DEFAULT 'S/D',
    evaluador VARCHAR(255) DEFAULT 'S/D',
    tipo_atencion TEXT NOT NULL,
    fecha_entrevista DATE,
    hora_entrevista TIME,
    defensor VARCHAR(100) DEFAULT 'S/D',
    tipo_riesgo VARCHAR(100) NOT NULL DEFAULT 'S/D',
    riesgo_168 VARCHAR(2) NULL,
    riesgo_169 VARCHAR(2) NULL,
    riesgo_170 VARCHAR(2) NULL,
    fecha_envio DATE,
    hora_envio TIME,
    estado varchar(15),
    verificado varchar(5),
    tipo_verificacion varchar(100),
    observaciones TEXT) ENGINE=InnoDB DEFAULT CHARSET=utf8;

    CREATE TABLE IF NOT EXISTS medidas_adolescentes(
	supervision VARCHAR(30) NOT NULL,
	fecha_solicitud DATE NOT NULL,
	evaluacion VARCHAR(30) DEFAULT 'S/D',
	paterno VARCHAR(100) NOT NULL,
	materno VARCHAR(100) NOT NULL,
	nombre VARCHAR(100) NOT NULL,
    edad INT,
	no_causa VARCHAR(255) NOT NULL,
	juez_control VARCHAR(100) NOT NULL,
	juzgado_control	VARCHAR(100) NOT NULL,
	distrito_judicial VARCHAR(100) NOT NULL,
	supervisor	VARCHAR(100) DEFAULT 'S/D',
	municipio	VARCHAR(100) DEFAULT 'S/D',
    colonia VARCHAR(256) DEFAULT 'S/D',
    calle VARCHAR(256) DEFAULT 'S/D',
    numero VARCHAR(256) DEFAULT 'S/D',
	delito TEXT,
	descripcion_delito	TEXT,
	seguimiento	VARCHAR(255) DEFAULT 'S/D',
	fecha_inicio_medida	DATE,
	fecha_termino_medida DATE,
	fecha_conclusion_medida	DATE,
	medida1	VARCHAR(2) DEFAULT 'NO',
	medida2	VARCHAR(2) DEFAULT 'NO',
	medida3	VARCHAR(2) DEFAULT 'NO',
	medida4	VARCHAR(2) DEFAULT 'NO',
	medida5	VARCHAR(2) DEFAULT 'NO',
	medida6	VARCHAR(2) DEFAULT 'NO',
	medida7	VARCHAR(2) DEFAULT 'NO',
	medida8	VARCHAR(2) DEFAULT 'NO',
	medida9	VARCHAR(2) DEFAULT 'NO',
	medida10 VARCHAR(2) DEFAULT 'NO',
	medida11 VARCHAR(2) DEFAULT 'NO',
	medida12 VARCHAR(2) DEFAULT 'NO',
    cantidad_medidas INTEGER NULL,
	medidas_dictadas TEXT,
	cumplimiento VARCHAR(30) DEFAULT 'S/D',
    fecha_incumplimiento DATE,
    medida_incumplida VARCHAR(100),
	fecha_modificacion DATE,
	tipo_modificacion TEXT,
	fecha_modificacion2	DATE,
	tipo_modificacion2 TEXT,
    proxima_audiencia DATE NULL,
    audiencias_asistidas VARCHAR(20) NULL,
    total_audiencias VARCHAR(20) NULL,
	tta	VARCHAR(255) DEFAULT 'S/D',
	observaciones TEXT,
    sexo VARCHAR(30),
    ultima_accion TEXT,
    forma_conclusion VARCHAR(100)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

    CREATE TABLE IF NOT EXISTS condiciones_adolescentes(
	supervision VARCHAR(30) NOT NULL,
	fecha_solicitud DATE NOT NULL,
	evaluacion VARCHAR(30) DEFAULT 'S/D',
	paterno VARCHAR(100) NOT NULL,
	materno VARCHAR(100) NOT NULL,
	nombre VARCHAR(100) NOT NULL,
    edad INT,
	no_causa VARCHAR(255) NOT NULL,
	juez_control VARCHAR(100) NOT NULL,
	juzgado_control	VARCHAR(100) NOT NULL,
	distrito_judicial VARCHAR(100) NOT NULL,
	supervisor	VARCHAR(100) DEFAULT 'S/D',
	municipio	VARCHAR(100) DEFAULT 'S/D',
    colonia VARCHAR(256) DEFAULT 'S/D',
    calle VARCHAR(256) DEFAULT 'S/D',
    numero VARCHAR(256) DEFAULT 'S/D',
	delito TEXT,
	descripcion_delito	TEXT,
	seguimiento	VARCHAR(50)	DEFAULT 'S/D',
	fecha_inicio_condicionantes	DATE,
	fecha_termino_condicionantes DATE,
	fecha_conclusion_condicionantes	DATE,
	condicion1 VARCHAR(2) DEFAULT 'NO',
	condicion2 VARCHAR(2) DEFAULT 'NO',
	condicion3 VARCHAR(2) DEFAULT 'NO',
	condicion4 VARCHAR(2) DEFAULT 'NO',
	condicion5 VARCHAR(2) DEFAULT 'NO',
	condicion6 VARCHAR(2) DEFAULT 'NO',
	condicion7 VARCHAR(2) DEFAULT 'NO',
	cantidad_condiciones INTEGER NULL,
	condiciones_dictadas TEXT,
	cumplimiento VARCHAR(30) DEFAULT 'S/D',
    fecha_incumplimiento DATE,
    condicion_incumplida VARCHAR(100),
	fecha_modificacion DATE,
	tipo_modificacion TEXT,
	fecha_modificacion2	DATE,
	tipo_modificacion2 TEXT,
    proxima_audiencia DATE NULL,
    audiencias_asistidas VARCHAR(20) NULL,
    total_audiencias VARCHAR(20) NULL,
	tta	VARCHAR(255) DEFAULT 'S/D',
	observaciones TEXT,
    sexo VARCHAR(30),
    ultima_accion TEXT,
    forma_conclusion VARCHAR(100)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

    CREATE TABLE IF NOT EXISTS colab_medidas_adolescentes(
	supervision VARCHAR(30) NOT NULL,
	fecha_solicitud DATE NOT NULL,
	colaboracion VARCHAR(30) DEFAULT 'S/D',
	paterno VARCHAR(100) NOT NULL,
	materno VARCHAR(100) NOT NULL,
	nombre VARCHAR(100) NOT NULL,
    edad INT,
	no_causa VARCHAR(255) NOT NULL,
	solicitante TEXT,
	procedencia VARCHAR(100) DEFAULT 'S/D',
    juez_control VARCHAR(255) DEFAULT 'S/D',
    juzgado_control	VARCHAR(100) DEFAULT 'S/D',
	distrito_judicial VARCHAR(100) DEFAULT 'S/D',
	municipio VARCHAR(256) DEFAULT 'S/D',
    colonia VARCHAR(256) DEFAULT 'S/D',
    calle VARCHAR(256) DEFAULT 'S/D',
    numero VARCHAR(256) DEFAULT 'S/D',
	delito TEXT,
	descripcion_delito	TEXT,
	seguimiento	VARCHAR(255) DEFAULT 'S/D',
	fecha_inicio_medida	DATE,
	fecha_termino_medida DATE,
	fecha_conclusion_medida	DATE,
	medida1	VARCHAR(2)	DEFAULT 'NO',
	medida2	VARCHAR(2)	DEFAULT 'NO',
	medida3	VARCHAR(2)	DEFAULT 'NO',
	medida4	VARCHAR(2)	DEFAULT 'NO',
	medida5	VARCHAR(2)	DEFAULT 'NO',
	medida6	VARCHAR(2)	DEFAULT 'NO',
	medida7	VARCHAR(2)	DEFAULT 'NO',
	medida8	VARCHAR(2)	DEFAULT 'NO',
	medida9	VARCHAR(2)	DEFAULT 'NO',
	medida10 VARCHAR(2) DEFAULT 'NO',
	medida11 VARCHAR(2) DEFAULT 'NO',
	medida12 VARCHAR(2) DEFAULT 'NO',
	cantidad_medidas INTEGER NULL,
	medidas_dictadas TEXT,
	cumplimiento VARCHAR(30) DEFAULT 'S/D',
    fecha_incumplimiento DATE,
    medida_incumplida VARCHAR(100),
	fecha_modificacion DATE,
	tipo_modificacion TEXT,
	fecha_modificacion2	DATE,
	tipo_modificacion2 TEXT,
    proxima_audiencia DATE NULL,
    audiencias_asistidas VARCHAR(20) NULL,
    total_audiencias VARCHAR(20) NULL,
	tta	VARCHAR(255) DEFAULT 'S/D',
	observaciones TEXT,   
    supervisor VARCHAR(256) NOT NULL,
	sexo VARCHAR(30),
    ultima_accion TEXT,
    forma_conclusion VARCHAR(100)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

    CREATE TABLE IF NOT EXISTS colab_condiciones_adolescentes(
	supervision VARCHAR(30) NOT NULL,
	fecha_solicitud DATE NOT NULL,
	colaboracion VARCHAR(30) DEFAULT 'S/D',
	paterno VARCHAR(100) NOT NULL,
	materno VARCHAR(100) NOT NULL,
	nombre VARCHAR(100) NOT NULL,
    edad INT,
	no_causa VARCHAR(255) NOT NULL,
	solicitante TEXT,
	procedencia VARCHAR(100) DEFAULT 'S/D',
    juez_control VARCHAR(255) DEFAULT 'S/D',
    juzgado_control	VARCHAR(100) DEFAULT 'S/D',
	distrito_judicial VARCHAR(100) DEFAULT 'S/D',
	municipio VARCHAR(256) DEFAULT 'S/D',
    colonia VARCHAR(256) DEFAULT 'S/D',
    calle VARCHAR(256) DEFAULT 'S/D',
    numero VARCHAR(256) DEFAULT 'S/D',
	delito TEXT,
	descripcion_delito	TEXT,
	seguimiento	VARCHAR(255) DEFAULT 'S/D',
	fecha_inicio_condicionantes	DATE,
	fecha_termino_condicionantes DATE,
	fecha_conclusion_condicionantes	DATE,
	condicion1 VARCHAR(2) DEFAULT 'NO',
	condicion2 VARCHAR(2) DEFAULT 'NO',
	condicion3 VARCHAR(2) DEFAULT 'NO',
	condicion4 VARCHAR(2) DEFAULT 'NO',
	condicion5 VARCHAR(2) DEFAULT 'NO',
	condicion6 VARCHAR(2) DEFAULT 'NO',
	condicion7 VARCHAR(2) DEFAULT 'NO',
	cantidad_condiciones INTEGER NULL,
	condiciones_dictadas TEXT,
	cumplimiento VARCHAR(30) DEFAULT 'S/D',
    fecha_incumplimiento DATE,
    condicion_incumplida VARCHAR(100),
	fecha_modificacion DATE,
	tipo_modificacion TEXT,
	fecha_modificacion2	DATE,
	tipo_modificacion2 TEXT,
    proxima_audiencia DATE NULL,
    audiencias_asistidas VARCHAR(20) NULL,
    total_audiencias VARCHAR(20) NULL,
	tta	VARCHAR(255) DEFAULT 'S/D',
	observaciones TEXT,
	supervisor VARCHAR(256) NOT NULL,
    sexo VARCHAR(30),
    ultima_accion TEXT,
    forma_conclusion VARCHAR(100)) ENGINE=InnoDB DEFAULT CHARSET=utf8;