CREATE DATABASE IF NOT EXISTS sigeca;

USE sigeca;

DROP TABLE IF EXISTS eval_adolescentes;
DROP TABLE IF EXISTS reevaluaciones;

CREATE TABLE IF NOT EXISTS tipos_usuario (
    id INT NOT NULL AUTO_INCREMENT,
    tipo VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS usuario (
    idusuario INT NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(50) NOT NULL,
    usuario VARCHAR(20) NOT NULL,
    contrasena VARCHAR(20) NOT NULL,
    fecha_alta DATE NOT NULL,
    tipo_usuario_id INT,
    estado TINYINT(1) NULL DEFAULT 1,
    PRIMARY KEY (idusuario),
    FOREIGN KEY (tipo_usuario_id) REFERENCES tipos_usuario(id)
);

CREATE TABLE IF NOT EXISTS eval_adolescentes (
    evaluacion VARCHAR(50),
    reevaluacion VARCHAR(50),
    carpeta_administrativa VARCHAR(100),
    juzgado VARCHAR(255),
    fecha_recepcion DATE,
    hora_recepcion TIME,
    fuero VARCHAR(50),
    fiscalia VARCHAR(255),
    agencia VARCHAR(255),
    ministerio_publico VARCHAR(255),
    turno VARCHAR(50),
    telefono VARCHAR(50),
    email VARCHAR(255),
    carpeta_investigacion VARCHAR(255),
    falla_tecnica VARCHAR(100),
    nuc VARCHAR(100),
    nic VARCHAR(100),
    fecha_disposicion DATE,
    hora_disposicion TIME,
    puesta_disposicion VARCHAR(100),
    paterno VARCHAR(50),
    materno VARCHAR(50),
    nombre VARCHAR(50),
    curp VARCHAR(50),
    edad TINYINT,
    genero VARCHAR(20),
    municipio VARCHAR(100),
    colonia VARCHAR(100),
    calle VARCHAR(100),
    numero VARCHAR(50),
    municipio_delito VARCHAR(100),
    colonia_delito VARCHAR(100),
    descripcion_delito VARCHAR(255),
    catalogo1 VARCHAR(50),
    catalogo2 VARCHAR(50),
    catalogo3 VARCHAR(50),
    catalogo4 VARCHAR(50),
    subdireccion VARCHAR(100),
    distrito_judicial VARCHAR(100),
    evaluador VARCHAR(100),
    tipo_atencion VARCHAR(100),
    tutor VARCHAR(100),
    fecha_entrevista DATE,
    hora_entrevista TIME,
    defensor VARCHAR(100),
    tipo_riesgo VARCHAR(50),
    riesgo_168 VARCHAR(50),
    riesgo_169 VARCHAR(50),
    riesgo_170 VARCHAR(50),
    fecha_envio DATE,
    hora_envio TIME,
    estado VARCHAR(50),
    verificado VARCHAR(10),
    tipo_verificacion VARCHAR(50),
    observaciones TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS reevaluaciones (
    evaluacion VARCHAR(50),
    reevaluacion VARCHAR(50),
    carpeta_administrativa VARCHAR(100),
    juzgado VARCHAR(255),
    fecha_recepcion DATE,
    hora_recepcion TIME,
    fuero VARCHAR(50),
    fiscalia VARCHAR(255),
    agencia VARCHAR(255),
    juez_control VARCHAR(255),
    turno VARCHAR(50),
    telefono VARCHAR(50),
    email VARCHAR(255),
    carpeta_investigacion VARCHAR(255),
    falla_tecnica VARCHAR(100),
    nuc VARCHAR(100),
    nic VARCHAR(100),
    fecha_disposicion DATE,
    hora_disposicion TIME,
    puesta_disposicion VARCHAR(100),
    paterno VARCHAR(50),
    materno VARCHAR(50),
    nombre VARCHAR(50),
    curp VARCHAR(50),
    rfc VARCHAR(50),
    edad TINYINT,
    genero VARCHAR(20),
    municipio VARCHAR(100),
    colonia VARCHAR(100),
    calle VARCHAR(100),
    numero VARCHAR(50),
    municipio_delito VARCHAR(100),
    colonia_delito VARCHAR(100),
    descripcion_delito VARCHAR(255),
    delito1 VARCHAR(255),
    delito2 VARCHAR(255),
    delito3 VARCHAR(255),
    delito4 VARCHAR(255),
    subdireccion VARCHAR(100),
    distrito_judicial VARCHAR(100),
    evaluador VARCHAR(100),
    tipo_atencion VARCHAR(100),
    fecha_entrevista DATE,
    hora_entrevista TIME,
    defensor VARCHAR(100),
    tipo_riesgo VARCHAR(50),
    nuevo_tipo_riesgo VARCHAR(50),
    riesgo168 VARCHAR(50),
    riesgo169 VARCHAR(50),
    riesgo170 VARCHAR(50),
    fecha_envio DATE,
    hora_envio TIME,
    estado VARCHAR(50),
    verificada VARCHAR(10),
    tipo_verificacion VARCHAR(50),
    observaciones TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
